### ISSUE TITLE
Cannot generate with any configs

### ISSUE THREAD

**Issue by therocco** [forknote/cryptonote-generator#22]
There is currently an issue with the `bytecoin` tests that is preventing coins from being generated. The issue appears to exists in the `/tests/CMakeLists.txt` file in the `bytecoin` repo. Specifically lines 32-36:

```
add_executable(NodeRpcProxyTests ${NodeRpcProxyTests})
add_executable(PerformanceTests ${PerformanceTests})
add_executable(SystemTests ${SystemTests})
add_executable(TransfersTests ${TransfersTests})
add_executable(UnitTests ${UnitTests})
```

I have created a ticket for it in the bytecoin repo (https://github.com/amjuarez/bytecoin/issues/110) but am including it here in case you wanted to add an exception to the build process to capture error and negate it. I fixed it on my end by removing line 152 of `generated_files/bytecoin/CMakeLists.txt` which is `add_subdirectory(tests)`

**Comment by pmitchev** [comment]
Do you still have this issue?
