### ISSUE TITLE
bug-fixes.json extension errors

### ISSUE THREAD

**Issue by therocco** [forknote/cryptonote-generator#23]
When including the `bug-fixes.json` extension generation of new coin fails. The issue seems to be in line 166-179:

```
    {
      "path": "/src/CryptoNoteCore/DatabaseBlockchainCache.cpp",
      "changes": [
        {
          "action": "replace",
          "marker": "cacheStart = 1;",
          "parameters": {
            "text": [
              "  cacheStart = 0;"
            ]
          }
        }
      ]
    },
```
compile fails because `cacheStart` is not found. Fixed issue by removing line block.

**Comment by pmitchev** [comment]
We are still testing the newest version. If you want to generate, use v2.0.1 as core by adding those lines here:

https://github.com/forknote/cryptonote-generator/blob/master/generator.sh#L44

`	cd ${BASE_COIN_PATH}
	git checkout d56f1c51664d9868403480867e8e68df49993e1e
	cd -`

**Comment by therocco** [comment]
That was quick! Thanks for the fast reply @pmitchev. I will check out the new branch when I get home.
