### ISSUE TITLE
Installation Issue on Running Generator.sh

### ISSUE THREAD

**Issue by andrewkoski** [forknote/cryptonote-generator#26]
**When I run;**

> bash generator.sh -f config.json

**I get the following error;**

> /root/generator/extensions/core/bytecoin.json
Making pre-tests in file /root/generator/generated_files/tmp/src/CMakeLists.txt
Traceback (most recent call last):
  File "lib/file-modification.py", line 164, in <module>
    for line in fileinput.input([args.source + file['path']], inplace=True):
  File "/usr/lib/python2.7/fileinput.py", line 237, in next
    line = self._readline()
  File "/usr/lib/python2.7/fileinput.py", line 316, in _readline
    os.rename(self._filename, self._backupfilename)
OSError: [Errno 2] No such file or directory

I am running Ubuntu 16.04.3 LTS and ran install_dependencies.sh with no issues whatsoever.

**Comment by JamesKegel** [comment]
you're missing a comma in your json
