### ISSUE TITLE
cant generate genesis hex Failed to parse arguments: Failed to initialize currency object (CLOSED)

### ISSUE THREAD

**Issue by lanaiscool** [forknote/cryptonote-generator#33]
when i try to print the genesis tx hex it says 
Failed to parse arguments: Failed to initialize currency object

**Comment by shopglobal** [comment]
same here

**Comment by pmitchev** [comment]
share your configs and what command you use

**Comment by shopglobal** [comment]
Think we had a string for "MONEY_SUPPLY" instead of an integer

**Comment by lanaiscool** [comment]
I did just as the guide told me however i deleted the value filled in for geneses ts hex i stead of leaving the one that the config generator uses is this wring should i leave the value there ? And tben recompile and then print a new hex ?

**Comment by lanaiscool** [comment]
@shopglobal you still having ths issue ?

**Comment by lanaiscool** [comment]
exact output:
`nick@nick-Aspire-A515-51G:~/Downloads/generator/generated_files/streamcoin/build/release/src$ ./streamcoind
2017-Dec-05 10:27:03.562535 INFO    streamcoin v2.1.2.1251 ()
2017-Dec-05 10:27:03.562917 INFO    Module folder: ./streamcoind
2017-Dec-05 10:27:03.563203 ERROR   failed to parse coinbase tx from hard coded blob
2017-Dec-05 10:27:03.563343 ERROR   Failed to generate genesis block
GENESIS_COINBASE_TX_HEX constant has an incorrect value. Please launch: streamcoind --print-genesis-txnick@nick-Aspire-A515-51G:~/Downloads/generator/generated_files/streamcoin/build/release/src$ ./streamcoind
2017-Dec-05 10:27:12.827292 INFO    streamcoin v2.1.2.1251 ()
2017-Dec-05 10:27:12.827701 INFO    Module folder: ./streamcoind
2017-Dec-05 10:27:12.827992 ERROR   failed to parse coinbase tx from hard coded blob
2017-Dec-05 10:27:12.828125 ERROR   Failed to generate genesis block
GENESIS_COINBASE_TX_HEX constant has an incorrect value. Please launch: streamcoind --print-genesis-txnick@nick-Aspire-A515-51G:~/Downloads/generator/generated_files/streamcoin/build/release/src$ ./streamcoind --print-genesis-tx
Failed to parse arguments: Failed to initialize currency object
Allowed options:

`

**Comment by lanaiscool** [comment]
I fixed it apparentley it needs a dummy tx hex

**Comment by lanaiscool** [comment]
Please close and please add it as note here and in the config as comment thanks

**Comment by koopa23** [comment]
i did all as the guide says and i am getting this error trying to print genesis tx 

Failed to parse arguments: unrecognised option 'rpcuser'

any solution for this?

**Comment by gldneagl** [comment]
Closed?? without someone adding how they got past the error??

**Comment by inzider** [comment]
Put a dummy tx hex instead of a empty space.
