### ISSUE TITLE
json rpc invalid request 

### ISSUE THREAD

**Issue by lanaiscool** [forknote/cryptonote-generator#38]
i tried various json rpc clients and i keep getting the same error message invalid request i tried this but still invalid request
curl -X POST --data '{"jsonrpc":"2.0","method":"getStatus","params":[],"id":1}‌​' http://localhost:8070/json_rpc

**Comment by pmitchev** [comment]
curl -X POST -i -H "Accept: application/json" -d '{"params": {},"jsonrpc": "2.0", "id": "test","method":"getStatus"}' http://localhost:8070/json_rpc

100% working. If not, check your walletd port

**Comment by lanaiscool** [comment]
Yes that command is working the problem was because of [] in parameters instead of {} thanks now i can modify the php client so it puts {} instead of [] thanks!
