### ISSUE TITLE
std::cout issue

### ISSUE THREAD

**Issue by zhmrab** [forknote/cryptonote-generator#42]
I've been trying to run the generator for a while and keep on bumping into the same issue, 
has anyone seen this?

/src/CryptoNoteCore/SwappedMap.h:198:8: error: no member named 'cout' in namespace 'std' ?

**Comment by pmitchev** [comment]
include extension "bug_fixes.json"

**Comment by zhmrab** [comment]
Thanks! Where do I include the extension?

**Comment by zhmrab** [comment]
I found the error, 

// where missing before std::cout in SwappedMap.h

//std::cout << "SwappedMap cache hits: " <

**Comment by BalajiM1995** [comment]
no member named 'cout' in namespace 'std'
  std::cout << "SwappedMap cache hits: " << m_cacheHits << ", misses: " ...
  ~~~~~^
1 error generated.
make[3]: *** [src/CMakeFiles/CryptoNoteCore.dir/CryptoNoteCore/SwappedMap.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/CryptoNoteCore.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [build-release] Error 2
