### ISSUE TITLE
How to setup config with old coin from Cryptonote Repo?

### ISSUE THREAD

**Issue by nidscom** [forknote/cryptonote-generator#43]
Hi. I tried to config cryptonote generator but im stuck. I have workable coin and want to update to latest bytecoin. Current version having problem with json rpc.  im stuck at this part

CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX
If referring to cryptonotestarter the prefix is different. Certainly start with 0x. My coin is based on fork from Cryptonote repo. How to fill address prefix so it will be the same. i try and error..not useful. and my wallet does not start with numbers. is there any tools to do this?

**Comment by nidscom** [comment]
I tried and have not yet find a proper way to do this. Reopen this case, hoping to find some light 😑

**Comment by pmitchev** [comment]
convert to decimal

**Comment by RocksteadyTC** [comment]
@nidscom post your base58 and I'll convert it for you

**Comment by nidscom** [comment]
Here it is. 0xbfdc7d5 @RocksteadyTC

**Comment by RocksteadyTC** [comment]
201181141
This creates the prefix "ciphs". I derived this by inputting bfdc7d5 into a hexadecimal to decimal converter https://www.binaryhexconverter.com/hex-to-decimal-converter
@nidscom

**Comment by nidscom** [comment]
awesome 😄 Thanks @RocksteadyTC. If i may..2nd. Do i need to convert random bytecoin network to decimal too? Mine is 0xe, 0x1 and so on (as from cryptonote).
