### ISSUE TITLE
testing transaction-extra-message-tag.json

### ISSUE THREAD

**Issue by RocksteadyTC** [forknote/cryptonote-generator#44]
I'm unable to see any obvious issues flipping through the extension, but "Still incompatible with Bytecoin clones" is listed in the general description. Before I set up a new testnet, is this extension not suggested to be used currently, or does the description imply that merge mining with Bytecoin is not working, while tx-extra is working, or vice versa?

https://github.com/forknote/cryptonote-generator/blob/master/extensions/transaction-extra-message-tag.json

Question is directed to @pmitchev, but I will accept any qualified answer.

**Comment by pmitchev** [comment]
This extension is work in progress. Also, it is meant just for new blockchains

**Comment by RocksteadyTC** [comment]
This presents an interesting challenge.
