### ISSUE TITLE
Premined coins

### ISSUE THREAD

**Issue by StyleShit** [forknote/cryptonote-generator#49]
How do I get the premined coins?
I created a config JSON using this tool: http://forknote.net/create/
and when I put a wallet address, it doens't even appear in the config response...
Where do I get the wallet address anyway?

**Comment by zhmrab** [comment]
Open simplewallet and generate a new address then start the deamon with --genesis-block-reward-address youradress

**Comment by StyleShit** [comment]
@zhmrab 
The daemon returns error:
"Failed to connect to any of seed peers, continuing without seeds"

**Comment by zhmrab** [comment]
Hmm that sounds like your seed nodes are not even connected, 

./yourcoind --print-genesis-tx  --genesis-block-reward-address youradress 
then copy the hex to your config and generate another time, 

also remember to delete the blockchain DB folder rm -rf ~/.yourcoin/ so there are no conflicts

**Comment by StyleShit** [comment]
@zhmrab
Why there is no a step-by-step explanation of how to use this generator?
Can u explain the steps needed for the process?
What I did so far is compiling the coin using the generator. What's next? how to I create the nodes and how do I compile a GUI wallet for linux / windows?

Thank you very much! :)

**Comment by zhmrab** [comment]
@StyleShit this message is because you are missing boost dependencies, it's all explained in the README.md  

:)

**Comment by 3ch0elite** [comment]
First off Props 100% on this you are the man. My question or issue with premine is simple wallet doesnt recognize --config-file from "./simplewallet --config-file configs/dashcoin.conf --generate-new-wallet MY.wallet --password PASSWORD". Also do i need to make a /configs file and put mycoin.conf in it? if so where should i put it? 
Thanks alot really great work cant wait to see dev on monero project.

**Comment by 3ch0elite** [comment]
Can you further expand on these

dir path to config?
Dir path of db blockchain to delete?
How to generate?

Im just worried that adding tx to coin.json and regenerating will just delete over created wallet...

Thanks alot love the work on this project!

**Comment by StyleShit** [comment]
@zhmrab I already installed the dependencies using the .sh file, but it installed libboost1.58, while it asked for 1.54, so I created symlinks from 1.58 folders to 1.54.

**Comment by StyleShit** [comment]
@zhmrab when I use ./mycoind --genesis-block-reward-address it doesn't work, and shows me the help message with available parameters.

**Comment by zhmrab** [comment]
You need to use it like this
./yourcoind —config-file configs/yourcoin.conf —print-genesis-tx —genesis-block-reward-address yourwallet

And then copy the hex into your config file

**Comment by StyleShit** [comment]
@zhmrab I dont't have a conf file. Where should it be?

**Comment by zhmrab** [comment]
forknote.net go to create and make one

**Comment by 3ch0elite** [comment]
What config file can give me dir? You know theres many different ones? Everything works for me. But i put tx in coin.json and generated.sh when i connect seed and mine, the wallet i transfered premine to says something like blockgenesis not the same as expected. Then i just get regular mined blocks. But not my premine showing?

Config dir?
And what to run after cause im guessing its not generator.sh???

Please let me know so i can get my stronger seed server set up.

**Comment by nskuijpers** [comment]
I have similar situation if I run —print-genesis-tx --genesis-block-reward-address youradress after creating a wallet and recompile the daemon and then start again de blockchain and try to open the wallet I get the message wrong genesis.

**Comment by michaellu88** [comment]
hi guys,
i follow this procedure, is that correct?
1. running 2 vps with configuration file(1)
2. running personalMac configuration file(1)
3. ./simplewallet create new address on configuration file(1) with (address A generated)
4. print-genesis-tx with configuration(1) with genesis-block-reward address (address A) and new tx_hex (hex A)
5. create a new configuration file (2) with the setting from configuration file (1) and replace tx_hex value and (reward address A) 
6.  delete configuration file(1) on 2 vps and personal and replace configuration file (2)
7. delete /.fakecoin/db folder
8. start ./forknote --config configuration file(2) on 2 vps and personalMac. create new db and running. sync ok
9. check wallet connected (address A). status ok
10. start_mining with ./miner 

when i start mining, the error said couldn't get block template: the stream is eneded

which procedure i doing wrong?

**Comment by pmitchev** [comment]
Complete procedure here:

http://forknote.net/guides/setup-private-blockchain/

If you find inaccuracies, the site is open source and you can submit fixes
