### ISSUE TITLE
Upstart > systemd, please help!

### ISSUE THREAD

**Issue by zhmrab** [forknote/cryptonote-generator#51]
Want to write the equivalent of an upstart in ubuntu 16 for my seed nodes but having some issues, basically want to convert into a systemd service on my servers,

description "mycoin daemon"

start on runlevel [23]
stop on shutdown

exec sudo -u fork /home/fork/generated_files/build/yourcoin-linux/yourcoind

post-stop exec sleep 30

respawn
respawn limit 5 30

**Comment by pmitchev** [comment]
[Unit]
Description= mycoin daemon

[Service]
WorkingDirectory=/root/
ExecStart=/usr/bin/nice -n0 /home/fork/generated_files/build/yourcoin-linux/yourcoind
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target

**Comment by zhmrab** [comment]
@pmitchev thank you!
