### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by D3monWolf2483** [forknote/cryptonote-generator#52]
cc1: all warnings being treated as errors
CMakeFiles/cmTC_5cc43.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_5cc43.dir/CheckFunctionExists.c.o' failed
make[1]: *** [CMakeFiles/cmTC_5cc43.dir/CheckFunctionExists.c.o] Error 1
make[1]: Leaving directory '/home/demon/generator/generated_files/d3moncoin/build/release/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_5cc43/fast' failed
make: *** [cmTC_5cc43/fast] Error 2

im new to this and dont understand this would like the help plz and thank you

**Comment by D3monWolf2483** [comment]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/miniupnpc
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/miniupnpc
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/miniupnpc
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/miniupnpc
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/gtest
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/gtest
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/gtest
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/gtest
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/external/gtest
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/src
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests
   used as include directory in directory /home/demon/generator/generated_files/d3moncoin/tests

-- Configuring incomplete, errors occurred!
See also "/home/demon/generator/generated_files/d3moncoin/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/demon/generator/generated_files/d3moncoin/build/release/CMakeFiles/CMakeError.log".
Remove temporary files...

**Comment by txponto** [comment]
Same problem, it seems like it's pulling the CMAKE from the bytecoin clone. I'm going to see what happens if I edit the bytecoin clone on my system before running the bash.

**Comment by pmitchev** [comment]
All replacements in the code are done by extensions. If you want to add custom code or make changes, you must make your own extension. Otherwise your changes will be wiped out
