### ISSUE TITLE
Correct implementation of zawy difficulty algorithm

### ISSUE THREAD

**Issue by luiscosio** [forknote/cryptonote-generator#57]
Hello!

What would be the correct extensions and configuration to use to correctly implement the zawy difficulty algorithm?

From the extension folders, there is a bunch of files and related commits and I'm not sure how to proceed (and it's not documented anywhere)

Here are the ones I think need to be applied:

- min-mixin.json
- mixin-start-height.json
- walletd-spent-transfers-tracking-mode.json
- zawy-difficulty-algorithm.json

Also, what configuration I should use?

-  "ZAWY_DIFFICULTY_V3": 1,
-  "ZAWY_DIFFICULTY_DIFFICULTY_BLOCK_VERSION": 3,

You can see my whole conf file in this repository:

https://github.com/inbestcoin/configs/blob/master/inbestcoin.json

**Comment by pmitchev** [comment]
You need this extensions:
* versionized-parameters.json
* zawy-difficulty-algorithm.json

You need this parameter for your configuration:
* "ZAWY_DIFFICULTY_BLOCK_INDEX": 123456

123456 is the block height.

ZAWY_DIFFICULTY_V2 and ZAWY_DIFFICULTY_V3 were deprecated in v2.12.
