### ISSUE TITLE
Generator Pulls Bytecoin clone unable to edit CMAKE

### ISSUE THREAD

**Issue by txponto** [forknote/cryptonote-generator#58]
As title states when I run bash generator a clone is pulled and the CMake with it. Leaving me unable to point it to my boost libs. I have tried deleting just my "coin" leaving the bytecoin clone and editing it in there but I'm still unable to get pass the boost libs. I know they work as I've tried with other source. Any pointers here?

**Comment by pmitchev** [comment]
All replacements in the code are done by extensions. If you want to add custom code or make changes, you must make your own extension. Otherwise your changes will be wiped out

**Comment by pmitchev** [comment]
All replacements in the code are done by extensions. If you want to add custom code or make changes, you must make your own extension. Otherwise your changes will be wiped out
