### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by samvicky26** [forknote/cryptonote-generator#68]
C:\Users\sam\Downloads\cryptonote-generator-master>bash generator.sh -f config.json
  File "lib/environment_variables.py", line 11
    print "export " + str(prefix) + str(key) + "=(" + " ".join(json.dumps(str(item)) for item in value) + ")"
                  ^
SyntaxError: invalid syntax
Remove temporary files... 

@pmitchev

**Comment by samvicky26** [comment]
looks like installing python 3.6.4 caused it, uninstalled it and installed python 2.7.9.But getting this error 

C:\Users\sam\Downloads\cryptonote-generator-master>bash generator.sh -f configs/forknote.json
Updating bytecoin...
Already up to date.
Make temporary bytecoin copy...
Personalize base coin source...
Execute /c/Users/sam/Downloads/cryptonote-generator-master/extensions/core/bytecoin.json
- Making pre-tests in file c:/Users/sam/Downloads/cryptonote-generator-master/generated_files/tmp/src/CMakeLists.txt
Traceback (most recent call last):
  File "lib/file-modification.py", line 206, in <module>
    for line in fileinput.input([args.source + file['path']], inplace=True):
  File "c:\Python27\lib\fileinput.py", line 252, in next
    line = self.readline()
  File "c:\Python27\lib\fileinput.py", line 321, in readline
    os.rename(self._filename, self._backupfilename)
WindowsError: [Error 3] The system cannot find the path specified
Remove temporary files...

**Comment by samvicky26** [comment]
I found the error bytecoin dev changed the repo address, that's why. please update the address

**Comment by lucaspojo** [comment]
Can u explain how to fix ? Thx

**Comment by pmitchev** [comment]
For now:
bash generator -f "config_file_path" -b "frozen-master"

I am modifying the code now to get it working by default

**Comment by hamzatrq** [comment]
Hi @pmitchev I have tried the command you mentioned 
bash generator -f "config_file_path" -b "frozen-master"

But -b is not an option in the generator. I am getting the following output
generator.sh: illegal option -- b
Usage: generator.sh [-h] [-f FILE] [-c <string>]
Reads a config file and creates and compiles Cryptonote coin. "config.json" as default

    -h          display this help and exit
    -f          config file
    -c          compile arguments
Remove temporary files...

**Comment by pmitchev** [comment]
You are right. It looks like it's still not pushed to the repo

**Comment by pmitchev** [comment]
fixed: https://github.com/forknote/cryptonote-generator/commit/7d29d1c1d9b64c26863fa2483a9aa5163bf1d3dc
