### ISSUE TITLE
Error build on windows 10

### ISSUE THREAD

**Issue by lucaspojo** [forknote/cryptonote-generator#69]
How to fix it ? ( work great on linux 16.04)

C:\Users\peneinc\Desktop\penecoin (master -> origin)
λ bash generator.sh -f config.json -c '/maxcpucount:3'
Updating bytecoin...
Already up to date.
Make temporary bytecoin copy...
Personalize base coin source...
Execute /c/Users/peneinc/Desktop/penecoin/extensions/core/bytecoin.json
- Making pre-tests in file C:/Users/peneinc/Desktop/penecoin/generated_files/tmp/src/CMakeLists.txt
Traceback (most recent call last):
  File "lib/file-modification.py", line 206, in <module>
    for line in fileinput.input([args.source + file['path']], inplace=True):
  File "C:\Python27\lib\fileinput.py", line 252, in next
    line = self.readline()
  File "C:\Python27\lib\fileinput.py", line 321, in readline
    os.rename(self._filename, self._backupfilename)
WindowsError: [Error 3] Le chemin dÆaccÞs spÚcifiÚ est introuvable
Remove temporary files...

**Comment by servc4** [comment]
Hi
Bytecoin move repo that's why is this error...
https://github.com/forknote/cryptonote-generator/issues/68

Regards

**Comment by lucaspojo** [comment]
@servc4 i have update my config : 
    "base_coin": {
        "name": "bytecoin",
        "git": "https://github.com/bcndev/bytecoin.git"
    },

But same error :s

**Comment by servc4** [comment]
Hi
But under this git is new release `Add a batch of release v3.0.0 commits  `

**Comment by lucaspojo** [comment]
Yes i add the new git : https://github.com/bcndev/bytecoin

But i have de same error, again ^^

**Comment by servc4** [comment]
Ok
But the generator is wrote to use Bytecoin v.2.1.2 release not release v3.0.0 commits
that's why is note working.

**Comment by lucaspojo** [comment]
Hooo !! Okey trans @servc4 !

Fix : 
Go to **/cryptonote-generator/generated_files** folder
Download this repo and extract to bytecoin folder : https://github.com/amjuarez/bytecoin/tree/frozen-master

Rebuild -> done :)

Thx !

**Comment by pmitchev** [comment]
Fixed: https://github.com/forknote/cryptonote-generator/commit/7d29d1c1d9b64c26863fa2483a9aa5163bf1d3dc
