### ISSUE TITLE
I can not generate a new currency

### ISSUE THREAD

**Issue by nullkalahar** [forknote/cryptonote-generator#71]
Error:

> root@vmi161760:~/generator# bash generator.sh -f config.json -c '-j3'
> Updating bytecoin...
> Already up-to-date.
> Make temporary bytecoin copy...
> Personalize base coin source...
> Execute /root/generator/extensions/core/bytecoin.json
> - Making pre-tests in file /root/generator/generated_files/tmp/src/CMakeLists.txt
> Traceback (most recent call last):
>   File "lib/file-modification.py", line 206, in <module>
>     for line in fileinput.input([args.source + file['path']], inplace=True):
>   File "/usr/lib/python2.7/fileinput.py", line 237, in next
>     line = self._readline()
>   File "/usr/lib/python2.7/fileinput.py", line 316, in _readline
>     os.rename(self._filename, self._backupfilename)
> OSError: [Errno 2] No such file or directory
> Remove temporary files...
> root@vmi161760:~/generator#

OS: Ubuntu 16.04
Command line: 
`bash install_dependencies.sh`
`bash generator.sh -f config.json -c '-j3'`
I used http://forknote.net/create/#/ to generate the configuration

**Comment by pmitchev** [comment]
git pull
