### ISSUE TITLE
Problem generating a new coin

### ISSUE THREAD

**Issue by luiscosio** [forknote/cryptonote-generator#72]
bash generator.sh -f configs/danielcoin.json -c '-j2'
ERROR: core config file does not exits
/home/ubuntu/cryptonote-generator/cores/.json

I see it's related to the new multicore structure, what would be the new command to generate a new coin?

**Comment by pmitchev** [comment]
I am updating the docs now. Basically, the only change you need to do is change this:
`"base_coin":{
	"name":"bytecoin",		
	"git":"https://github.com/amjuarez/bytecoin.git"
},`
with this:
`"base_coin": "bytecoin-v2",`

**Comment by luiscosio** [comment]
Thank you, I'll mark it as closed.
