### ISSUE TITLE
Generator error on MacOS

### ISSUE THREAD

**Issue by zhmrab** [forknote/cryptonote-generator#76]
Getting this when trying to generate my coin : 
 bash generator.sh -f coin.json

ERROR: core config file does not exits
/Users/Z/generator/cores/.json

**Comment by pmitchev** [comment]
The config format was changed in the last version.
You need to change this:
`"base_coin":{ "name":"bytecoin", "git":"https://github.com/amjuarez/bytecoin.git" },`
with this:
`"base_coin": "bytecoin-v2",`
